workflows:
  ios-build:
    name: uYouEnhanced Build
    instance_type: mac_mini_m2
    max_build_duration: 120
    environment:
      vars:
        BUNDLE_ID: "com.google.ios.youtube"
      xcode: latest
    scripts:
      - name: Build IPA
        script: |
          cd $CM_BUILD_DIR
          xcode-project build-ipa \
            --project "YouTube.xcodeproj" \
            --scheme "YouTube" \
            --archive-directory build/ios/xcarchive \
            --ipa-directory build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
